### ISSUE TITLE
Trying to store large file as efficient_recording_extractor causes connection error

### ISSUE THREAD

**Issue by lfrank** [flatironinstitute/labbox-ephys#474]
code:
`        labbox_recording = le.LabboxEphysRecordingExtractor.create_efficient_recording(recording)
`

Error:

Traceback (most recent call last):
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/loren/Src/NWB/notebooks/spikesorting_test.py", line 96, in <module>
    main()
  File "/home/loren/Src/NWB/notebooks/spikesorting_test.py", line 84, in main
    SpikeSorting.populate([(SpikeSortingParameters & {'nwb_file_name' : nwb_file_name, 'sort_interval_name' : sort_interval_name,
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/datajoint/autopopulate.py", line 153, in populate
    make(dict(key))
  File "/home/loren/Src/NWB/nwb_datajoint/src/nwb_datajoint/common/common_spikesorting.py", line 548, in make
    labbox_recording = le.LabboxEphysRecordingExtractor.create_efficient_recording(recording)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/labbox_ephys/extractors/labboxephysrecordingextractor.py", line 361, in create_efficient_recording
    h5_uri = kp.store_file(fname)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/kachery_p2p/main.py", line 155, in store_file
    return _store_file(path=path, basename=basename)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/kachery_p2p/_store_file.py", line 31, in _store_file
    resp = _http_post_file(url, os.path.abspath(path), headers=headers)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/kachery_p2p/_misc.py", line 118, in _http_post_file
    req = requests.post(url, data=f, headers=headers)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/loren/anaconda3/envs/nwb_datajoint/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Cleaning up parallel job handler

**Comment by magland** [comment]
I think for now this is solved by using linking method discussed elsewhere. Closing for now.
